include:
  - project: devops/ci-config
    ref: main
    file:
      - /templates/audit-jobs.gitlab-ci.yml
      - /templates/container-flexible.gitlab-ci.yml
      - /templates/environments.gitlab-ci.yml
      - /templates/tag-release-version.gitlab-ci.yml
      - /templates/submodule-workflow.gitlab-ci.yml

variables:
  COMMIT_MESSAGE: "Update submodule to latest commit"
  DOWNSTREAM_PROJECT: "papyri/papyri-docker"
  DOWNSTREAM_BRANCH: "master"


stages:
  - build
  - test
  - publish
  - deploy
  - tasks

.job:
  except:
    variables:
      - $CI_SKIP_JOB_STAGE == $CI_JOB_STAGE

build:
  extends: .build

test:
  extends: .test

integration-tests:
  stage: test
  extends: .trigger_downstream_pipeline
  variables:
    DOWNSTREAM_PROJECT: "papyri/papyri-docker"
    DOWNSTREAM_BRANCH: "master"
  allow_failure: true
  # Might be annoying to have this run on every commit, but it is useful to have
  when: manual

update_submodules:
  stage: publish
  extends: .update_submodule
  rules:
    - if: $CI_COMMIT_BRANCH == "master" && $CI_PIPELINE_SOURCE == "push"
  
publish:
  extends: .job
  tags:
    - publish
  stage: publish
  script:
    - make publish
  when: manual

deploy-prod-deb-12:
  tags:
    - deploy
  stage: deploy
  script:
    - CURRENT_TIME=$(date +%Y-%m-%d\ %H:%M:%S)
    - sudo /usr/bin/systemctl start papyri-navigator-deploy-playbook.service
    - sudo /usr/bin/journalctl -u papyri-navigator-deploy-playbook --since "${CURRENT_TIME}"
  when: manual

deploy-dev:
  tags:
    - deploy
  stage: deploy
  script:
    - CURRENT_TIME=$(date +%Y-%m-%d\ %H:%M:%S)
    - sudo /usr/bin/systemctl start papyri-navigator-dev-deploy-playbook.service
    - sudo /usr/bin/journalctl -u papyri-navigator-dev-deploy-playbook --since "${CURRENT_TIME}"
  when: manual

reindex-prod:
  tags:
    - tasks
  stage: tasks
  script:
    - CURRENT_TIME=$(date +%Y-%m-%d\ %H:%M:%S)
    - sudo /usr/bin/systemctl start papyri-navigator-indexing-playbook.service
    - ./poll-for-indexing-completion.sh papyri-navigator-indexing-playbook
    - sudo /usr/bin/journalctl -u papyri-navigator-indexing-playbook --since "${CURRENT_TIME}"
  when: manual

reindex-dev:
  tags:
    - tasks
  stage: tasks
  script:
    - CURRENT_TIME=$(date +%Y-%m-%d\ %H:%M:%S)
    - sudo /usr/bin/systemctl start papyri-navigator-indexing-dev-playbook.service
    - ./poll-for-indexing-completion.sh papyri-navigator-indexing-dev-playbook
    - sudo /usr/bin/journalctl -u papyri-navigator-indexing-dev-playbook --since "${CURRENT_TIME}"
  when: manual