include:
  - project: devops/ci-config
    file:
      - /templates/audit-jobs.gitlab-ci.yml
      - /templates/container-flexible.gitlab-ci.yml
      - /templates/environments.gitlab-ci.yml
      - /templates/tag-release-version.gitlab-ci.yml

stages:
  - build
  - test
  - publish
  - deploy

.job:
  except:
    variables:
      - $CI_SKIP_JOB_STAGE == $CI_JOB_STAGE

build:
  extends: .build

test:
  extends: .test

publish:
  extends: .job
  tags:
    - publish
  stage: publish
  script:
    - make publish
  when: manual

deploy-dev:
  tags:
    - deploy
  stage: deploy
  script:
    - CURRENT_TIME=$(date +%Y-%m-%d\ %H:%M:%S)
    - sudo /usr/bin/systemctl start papyri-navigator-playbook.service
    - sudo /usr/bin/journalctl -u papyri-navigator-playbook --since "${CURRENT_TIME}"
  when: manual

reindex:
  tags:
    - deploy
  stage: deploy
  script:
    - CURRENT_TIME=$(date +%Y-%m-%d\ %H:%M:%S)
    - sudo /usr/bin/systemctl start papyri-navigator-indexing-playbook.service
    - sudo ./poll-for-indexing-completion.sh "${CURRENT_TIME}"
  when: manual