include:
  - project: devops/ci-config
    file:
      - /templates/audit-jobs.gitlab-ci.yml
      - /templates/container-flexible.gitlab-ci.yml
      - /templates/environments.gitlab-ci.yml
      - /templates/tag-release-version.gitlab-ci.yml

stages:
  - build
  - test
  - deploy

.job:
  except:
    variables:
      - $CI_SKIP_JOB_STAGE == $CI_JOB_STAGE

build:
  extends: .build

test:
  extends: .test

publish:
  extends: .job
  tags:
    - publish
  stage: deploy
  script:
    - make publish
<<<<<<< HEAD
=======
  when: manual

deploy-prod-deb-12:
  tags:
    - deploy
  stage: deploy
  script:
    - CURRENT_TIME=$(date +%Y-%m-%d\ %H:%M:%S)
    - sudo /usr/bin/systemctl start papyri-navigator-deploy-playbook.service
    - sudo /usr/bin/journalctl -u papyri-navigator-deploy-playbook --since "${CURRENT_TIME}"
  when: manual

deploy-dev:
  tags:
    - deploy
  stage: deploy
  script:
    - CURRENT_TIME=$(date +%Y-%m-%d\ %H:%M:%S)
    - sudo /usr/bin/systemctl start papyri-navigator-dev-deploy-playbook.service
    - sudo /usr/bin/journalctl -u papyri-navigator-dev-deploy-playbook --since "${CURRENT_TIME}"
  when: manual

reindex-prod:
  tags:
    - tasks
  stage: tasks
  script:
    - CURRENT_TIME=$(date +%Y-%m-%d\ %H:%M:%S)
    - sudo /usr/bin/systemctl start papyri-navigator-indexing-playbook.service
    - ./poll-for-indexing-completion.sh papyri-navigator-indexing-playbook
    - sudo /usr/bin/journalctl -u papyri-navigator-indexing-playbook --since "${CURRENT_TIME}"
  when: manual

reindex-dev:
  tags:
    - tasks
  stage: tasks
  script:
    - CURRENT_TIME=$(date +%Y-%m-%d\ %H:%M:%S)
    - sudo /usr/bin/systemctl start papyri-navigator-indexing-dev-playbook.service
    - ./poll-for-indexing-completion.sh papyri-navigator-indexing-dev-playbook
    - sudo /usr/bin/journalctl -u papyri-navigator-indexing-dev-playbook --since "${CURRENT_TIME}"
>>>>>>> a90b82a5 (Add indexing for future prod environment and pass service for completion progress polling script)
  when: manual