include:
  - project: devops/ci-config
    file:
      - /templates/audit-jobs.gitlab-ci.yml
      - /templates/container-flexible.gitlab-ci.yml
      - /templates/environments.gitlab-ci.yml
      - /templates/tag-release-version.gitlab-ci.yml

stages:
  - build
  - test
  - publish
  - deploy

.job:
  except:
    variables:
      - $CI_SKIP_JOB_STAGE == $CI_JOB_STAGE

build:
  extends: .build

test:
  extends: .test

publish:
  extends: .job
  tags:
    - publish
  stage: publish
  script:
    - make publish
  when: manual

deploy-dev:
  tags:
    - deploy
  stage: deploy
  script:
    - CURRENT_TIME=$(date +%Y-%m-%d\ %H:%M:%S)
    - sudo /usr/bin/systemctl start papyri-navigator-playbook.service
    - sudo /usr/bin/journalctl -u papyri-navigator-playbook --since "${CURRENT_TIME}"
  when: manual

reindex:
  tags:
    - deploy
  stage: deploy
  script:
    - CURRENT_TIME=$(date +%Y-%m-%d\ %H:%M:%S)
    - delay=300
    - sudo /usr/bin/systemctl start papyri-navigator-indexing-playbook.service
    - sleep 5
    - |
      while true; do
        status=$(systemctl status $service_name | grep Active | awk '{print $2}');
        if [ "$status" == "failed" ]; then
            echo "Service failed to start";
            exit 1;
        elif [ "$status" == "inactive" ]; then
            echo "Service completed";
            break;
        elif [ "$status" == "active" ] || [ "$status" == "activating" ] || [ "$status" == "deactivating" ]; then
            echo "Indexing in progress...";
            sleep $delay;
            continue;
        else
            break;
        fi;
      done
    - sudo /usr/bin/journalctl -u papyri-navigator-indexing-playbook --since "${CURRENT_TIME}"
  when: manual