#!/usr/bin/python

import sys
import zlib

def main():
  input = sys.argv[1]
  output = sys.argv[2]
  fin = open(input, "rb")
  data = fin.read()
  zipped = zlib.compress(data, 1)
  fin.close()
  fout = open (output, "wb")
  fout.write(zipped)
  fout.close()

if __name__ == "__main__":
    sys.exit(main())
