package info.papyri.dispatch.browse;

    /* Names of fields indexed in Solr and used by the <code>FacetBrowser</code>,
     * <code>CollectionBrowser</code>, and <code>AtomFeedServlet</code> servlets.
     * 
     * @author: thill 
     */
public enum SolrField {
   
        all,
        apis_full_identifier,
        apis_inventory,
        apis_metadata,
        apis_publication_id,
        apis_series,
        collection,
        dclp_full_identifier,
        dclp_identifier,
        dclp_metadata,
        dclp_series,
        dclp_volume,
        ddbdp_full_identifier,
        ddbdp_series,
        ddbdp_volume,
        display_date,
        display_place,
        earliest_date,
        facet_language,
        full_identifier,
        has_transcription,
        has_translation,
        hgv_full_identifier,
        hgv_identifier,
        hgv_metadata,
        hgv_series,
        hgv_volume,
        id,
        identifier,
        idno_led_path,
        illustrations,
        images,
        images_ext,
        images_int,
        image_path,
        invnum,
        item,
        language,
        latest_date,        
        metadata,
        nome,
        series,
        series_led_path,
        title,
        transcription,
        transcription_ia,
        transcription_ic,
        transcription_id,
        transcription_ngram_ia,
        transcription_ngram_ic,
        transcription_ngram_id,
        translation,
        translation_language,
        translations,
        unknown_date_flag,
        untokenized,
        untokenized_ia,
        untokenized_ic,
        untokenized_id,
        volume,
        volume_led_path,
        
}
