{
items:[
	{
		index:0,
		label:"pts.apis.10",
		type:"Search Result",
		title:"Joshua 4:23-5:1, IV c. CE",
		"title-hgv":"",
		"title-apis":"Joshua 4:23-5:1, IV c. CE",
		title:"Joshua 4:23-5:1, IV c. CE",
		"has-image":"N",
		"image-url":"null",
		"image-url-label":"",
		"has-translation":"Y",
		publication:["P.Oxy. IX 1168","P.Oxy. 9","P.Oxy. IX 1168 p"],
		"publication-series":["P.Oxy."],
		apis:["pts.apis.10"],
		"apis-collection":["pts"],
inventory:"SCR 1034 (Box 2), item 3",
		lang:["Greek"],
date:"300 CE - 399 CE",
		provenance:["Oxyrhynchus"],
		"provenance-note":["Oxyrhynchus | Excavated by Grenfell and Hunt for the Egypt Exploration Fund (year unknown); donated to Princeton Theological Seminary in 1915 through an arrangement with Prof. William Park Armstrong."],
		"provenance-apis":["Oxyrhynchus"],
		"provenance-hgv":[],
		hgv:["none"],
		ddbdp:["P.Oxy.:9:1168"],
		ldab:["none"]	}
,
	{
		index:1,
		label:"pts.apis.11",
		type:"Search Result",
		title:"Matthew 6:5-6, 8-10, 13-15, 17, V/VI c. CE",
		"title-hgv":"",
		"title-apis":"Matthew 6:5-6, 8-10, 13-15, 17, V/VI c. CE",
		title:"Matthew 6:5-6, 8-10, 13-15, 17, V/VI c. CE",
		"has-image":"N",
		"image-url":"null",
		"image-url-label":"",
		"has-translation":"Y",
		publication:["P.Oxy. IX 1169","P.Oxy. 9","P.Oxy. IX 1169 p"],
		"publication-series":["P.Oxy."],
		apis:["pts.apis.11"],
		"apis-collection":["pts"],
inventory:"SCR 1034 (Box 2), item 4",
		lang:["Greek"],
date:"400 CE - 599 CE",
		provenance:["Oxyrhynchus"],
		"provenance-note":["Oxyrhynchus | Excavated by Grenfell and Hunt for the Egypt Exploration Fund (year unknown); donated to Princeton Theological Seminary in 1915 through an arrangment with Prof. William Park Armstrong."],
		"provenance-apis":["Oxyrhynchus"],
		"provenance-hgv":[],
		hgv:["none"],
		ddbdp:["P.Oxy.:9:1169"],
		ldab:["none"]	}
,
	{
		index:2,
		label:"pts.apis.12",
		type:"Search Result",
		title:"Leviticus 16:33-34, IV c. CE",
		"title-hgv":"",
		"title-apis":"Leviticus 16:33-34, IV c. CE",
		title:"Leviticus 16:33-34, IV c. CE",
		"has-image":"N",
		"image-url":"null",
		"image-url-label":"",
		"has-translation":"Y",
		publication:["P.Oxy. X 1225","P.Oxy. 10","P.Oxy. X 1225 p"],
		"publication-series":["P.Oxy."],
		apis:["pts.apis.12"],
		"apis-collection":["pts"],
inventory:"SCR 1036 (Box 4), item 3",
		lang:["Greek"],
date:"300 CE - 399 CE",
		provenance:["Oxyrhynchus"],
		"provenance-note":["Oxyrhynchus | Excavated by Grenfell and Hunt for the Egypt Exploration Fund in the 1903-1904 season; donated to Princeton Theological Seminary in 1915 through an arrangement with Prof. William Park Armstrong."],
		"provenance-apis":["Oxyrhynchus"],
		"provenance-hgv":[],
		hgv:["none"],
		ddbdp:["P.Oxy.:10:1225"],
		ldab:["none"]	}
,
	{
		index:3,
		label:"pts.apis.5",
		type:"Search Result",
		title:"Revelation 3:19-4:3, IV c. CE",
		"title-hgv":"",
		"title-apis":"Revelation 3:19-4:3, IV c. CE",
		title:"Revelation 3:19-4:3, IV c. CE",
		"has-image":"N",
		"image-url":"null",
		"image-url-label":"",
		"has-translation":"Y",
		publication:["P.Oxy. VIII 1080","P.Oxy. 8","P.Oxy. VIII 1080 p"],
		"publication-series":["P.Oxy."],
		apis:["pts.apis.5"],
		"apis-collection":["pts"],
inventory:"SCR 1034 (Box 2), item 1",
		lang:["Greek"],
date:"300 CE - 399 CE",
		provenance:["Oxyrhynchus"],
		"provenance-note":["Oxyrhynchus | Excavated by Grenfell and Hunt for the Egypt Exploration Fund in 1906; donated to Princeton Theological Seminary in 1915 through an arrangment with Prof. William Park Armstrong."],
		"provenance-apis":["Oxyrhynchus"],
		"provenance-hgv":[],
		hgv:["none"],
		ddbdp:["P.Oxy.:8:1080"],
		ldab:["none"]	}
,
	{
		index:4,
		label:"pts.apis.6",
		type:"Search Result",
		title:"Isocrates, Panegyricus and De Pace, IV c. CE",
		"title-hgv":"",
		"title-apis":"Isocrates, Panegyricus and De Pace, IV c. CE",
		title:"Isocrates, Panegyricus and De Pace, IV c. CE",
		"has-image":"N",
		"image-url":"null",
		"image-url-label":"",
		"has-translation":"Y",
		publication:["P.Oxy. VIII 1096","P.Oxy. 8","P.Oxy. VIII 1096 p"],
		"publication-series":["P.Oxy."],
		apis:["pts.apis.6"],
		"apis-collection":["pts"],
inventory:"SCR 1034 (Box 2), item 2",
		lang:["Greek"],
date:"300 CE - 399 CE",
		provenance:["Oxyrhynchus"],
		"provenance-note":["Oxyrhynchus | Excavated by Grenfell and Hunt for the Egypt Exploration Fund in 1906; donated to Princeton Theological Seminary in 1915 through an arrangment with Prof. William Park Armstrong."],
		"provenance-apis":["Oxyrhynchus"],
		"provenance-hgv":[],
		hgv:["none"],
		ddbdp:["P.Oxy.:8:1096"],
		ldab:["none"]	}
,
	{
		index:5,
		label:"pts.apis.9",
		type:"Search Result",
		title:"Genesis 31:42-46, 48-54, IV c. CE",
		"title-hgv":"",
		"title-apis":"Genesis 31:42-46, 48-54, IV c. CE",
		title:"Genesis 31:42-46, 48-54, IV c. CE",
		"has-image":"N",
		"image-url":"null",
		"image-url-label":"",
		"has-translation":"Y",
		publication:["P.Oxy. IX 1167","P.Oxy. 9","P.Oxy. IX 1167 p"],
		"publication-series":["P.Oxy."],
		apis:["pts.apis.9"],
		"apis-collection":["pts"],
inventory:"SCR 1035 (Box 3), item 4",
		lang:["Greek"],
date:"300 CE - 399 CE",
		provenance:["Oxyrhynchus"],
		"provenance-note":["Oxyrhynchus | Excavated by Grenfell and Hunt for the Egypt Exploration Fund (year unknown); donated to Princeton Theological Seminary in 1915 through an arrangment with Prof. William Park Armstrong."],
		"provenance-apis":["Oxyrhynchus"],
		"provenance-hgv":[],
		hgv:["none"],
		ddbdp:["P.Oxy.:9:1167"],
		ldab:["none"]	}
,
	{
		index:6,
		label:"P.Oxy. VI 903",
		type:"Search Result",
		title:"Accusation against a Husband",
		"title-hgv":"Accusation against a Husband",
		"title-apis":"Accusation against a Husband, IV c. CE",
		title:"Accusation against a Husband",
		"has-image":"N",
		"image-url":"null",
		"image-url-label":"",
		"has-translation":"Y",
		publication:["P.Oxy. VI 903"],
		"publication-series":["P.Oxy."],
		apis:["pts.apis.1"],
		"apis-collection":["pts"],
inventory:"SCR 1033 (Box 1)",
		lang:["Greek"],
date:"400 CE ",
		provenance:["Oxyrhynchos"],
		"provenance-note":["Oxyrhynchos"],
		"provenance-apis":["Oxyrhynchus"],
		"provenance-hgv":["Oxyrhynchos"],
		hgv:["P.Oxy. VI 903"],
		ddbdp:["none"],
		ldab:["none"]	}
,
	{
		index:7,
		label:"P.Oxy. VI 925",
		type:"Search Result",
		title:"Christian Prayer",
		"title-hgv":"Christian Prayer",
		"title-apis":"Christian Prayer, V/VI c. CE",
		title:"Christian Prayer",
		"has-image":"N",
		"image-url":"null",
		"image-url-label":"",
		"has-translation":"Y",
		publication:["P.Oxy. VI 925"],
		"publication-series":["P.Oxy."],
		apis:["pts.apis.2"],
		"apis-collection":["pts"],
inventory:"SCR 1035 (Box 3), item 1",
		lang:["Greek"],
date:"500 CE ",
		provenance:["Oxyrhynchos"],
		"provenance-note":["Oxyrhynchos"],
		"provenance-apis":["Oxyrhynchus"],
		"provenance-hgv":["Oxyrhynchos"],
		hgv:["P.Oxy. VI 925"],
		ddbdp:["none"],
		ldab:["none"]	}
,
	{
		index:8,
		label:"P.Oxy. VII 1058",
		type:"Search Result",
		title:"Christian Prayer",
		"title-hgv":"Christian Prayer",
		"title-apis":"Christian Prayer, IV/V c. CE",
		title:"Christian Prayer",
		"has-image":"N",
		"image-url":"null",
		"image-url-label":"",
		"has-translation":"Y",
		publication:["P.Oxy. VII 1058"],
		"publication-series":["P.Oxy."],
		apis:["pts.apis.3"],
		"apis-collection":["pts"],
inventory:"SCR 1036 (Box 4), item 1",
		lang:["Greek"],
date:"400 CE ",
		provenance:["Oxyrhynchos"],
		"provenance-note":["Oxyrhynchos"],
		"provenance-apis":["Oxyrhynchus"],
		"provenance-hgv":["Oxyrhynchos"],
		hgv:["P.Oxy. VII 1058"],
		ddbdp:["none"],
		ldab:["none"]	}
,
	{
		index:9,
		label:"P.Oxy. VII 1065",
		type:"Search Result",
		title:"Letter of Hephaestion",
		"title-hgv":"Letter of Hephaestion",
		"title-apis":"Letter of Hephaestion, III c. CE",
		title:"Letter of Hephaestion",
		"has-image":"N",
		"image-url":"null",
		"image-url-label":"",
		"has-translation":"Y",
		publication:["P.Oxy. VII 1065"],
		"publication-series":["P.Oxy."],
		apis:["pts.apis.4"],
		"apis-collection":["pts"],
inventory:"SCR 1035 (Box 3), item 2",
		lang:["Greek"],
date:"300 CE ",
		provenance:["Oxyrhynchos"],
		"provenance-note":["Oxyrhynchos"],
		"provenance-apis":["Oxyrhynchus"],
		"provenance-hgv":["Oxyrhynchos"],
		hgv:["P.Oxy. VII 1065"],
		ddbdp:["none"],
		ldab:["none"]	}
,
	{
		index:10,
		label:"P.Oxy. VIII 1138",
		type:"Search Result",
		title:"Receipt for Money - taxes",
		"title-hgv":"Receipt for Money - taxes",
		"title-apis":"Receipt for Money-taxes, V/VI c. CE",
		title:"Receipt for Money - taxes",
		"has-image":"N",
		"image-url":"null",
		"image-url-label":"",
		"has-translation":"Y",
		publication:["P.Oxy. VIII 1138"],
		"publication-series":["P.Oxy."],
		apis:["pts.apis.7"],
		"apis-collection":["pts"],
inventory:"SCR 1036 (Box 4), item 2",
		lang:["Greek"],
date:"500 CE ",
		provenance:["Oxyrhynchos"],
		"provenance-note":["Oxyrhynchos"],
		"provenance-apis":["Oxyrhunchus"],
		"provenance-hgv":["Oxyrhynchos"],
		hgv:["P.Oxy. VIII 1138"],
		ddbdp:["none"],
		ldab:["none"]	}
,
	{
		index:11,
		label:"P.Oxy. VIII 1152",
		type:"Search Result",
		title:"Christian Amulet",
		"title-hgv":"Christian Amulet",
		"title-apis":"Christian Amulet, V/VI c. CE",
		title:"Christian Amulet",
		"has-image":"N",
		"image-url":"null",
		"image-url-label":"",
		"has-translation":"Y",
		publication:["P.Oxy. VIII 1152"],
		"publication-series":["P.Oxy."],
		apis:["pts.apis.8"],
		"apis-collection":["pts"],
inventory:"SCR 1035 (Box 3), item 3",
		lang:["Greek"],
date:"500 CE ",
		provenance:["Oxyrhynchos"],
		"provenance-note":["Oxyrhynchos"],
		"provenance-apis":["Oxyrhynchus"],
		"provenance-hgv":["Oxyrhynchos"],
		hgv:["P.Oxy. VIII 1152"],
		ddbdp:["none"],
		ldab:["none"]	}
],
types: {'Search Result':{pluralLabel:'Search Results'}},
properties: {
'inventory':{valueType:"string",label:"Inventory No."},
'bl':{valueType:"string",label:"BL"},
'title':{valueType:"string",label:"Title"},
'title-apis':{valueType:"string",label:"Title"},
'title-hgv':{valueType:"string",label:"Title"},
'image-url':{valueType:"url",label:"Image URL"},
'image-url-label':{valueType:"string"},
'has-image':{valueType:"boolean",label:"Has Image"},
'has-translation':{valueType:"boolean",label:"Has Translation"},
'publication':{valueType:"string",label:"Publication"},
'publication-apis':{valueType:"string",label:"Publication"},
'publication-hgv':{valueType:"string",label:"Publication"},
'publication-series':{valueType:"string"},
'apis':{valueType:"string",label:"APIS Control Name"},
'apis-collection':{valueType:"string",label:"APIS Collection"},
'lang':{valueType:"string",label:"Language"},
'date':{valueType:"string",label:"Date"},
'date-apis':{valueType:"string",label:"Date"},
'date-hgv':{valueType:"string",label:"Date"},
'provenance':{valueType:"string",label:"Provenance"},
'provenance-apis':{valueType:"string",label:"Provenance"},
'provenance-hgv':{valueType:"string",label:"Provenance"},
'provenance-note':{valueType:"string"},
'hgv':{valueType:"string",label:"HGV ID"},
'ddbdp':{valueType:"string"},
'ldab':{valueType:"string"}
}
};
