task setup: [] do 
	if File.exists? "../epidoc-xslt"
		sh "cd ../epidoc-xslt; git pull"
	else
		sh "git clone https://github.com/EpiDoc/Stylesheets.git ../epidoc-xslt"
	end
end

task clean: [] do
	sh "rm -rf ../epidoc-xslt"
end
