# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev openjdk-11-jdk-headless maven git perl tar wget curl
    - name: Configure Maven
      run: mkdir -p ~/.m2 && cat .github/m2settings.xml | sed -e "s/MAVEN_GITHUB_USERNAME/${MAVEN_GITHUB_USERNAME}/" -e "s/MAVEN_GITHUB_TOKEN/${MAVEN_GITHUB_TOKEN}/" > ~/.m2/settings.xml
      env:
        MAVEN_GITHUB_USERNAME: ${{ secrets.MAVEN_GITHUB_USERNAME }}
        MAVEN_GITHUB_TOKEN: ${{ secrets.MAVEN_GITHUB_TOKEN }}
    - name: Install Fuseki
      run: sudo mkdir -p /opt/fuseki && wget --no-check-certificate https://archive.apache.org/dist/jena/binaries/apache-jena-fuseki-3.17.0.tar.gz -O-|sudo tar -zx --strip-components 1 -C /opt/fuseki/ apache-jena-fuseki-3.17.0
    - name: Run Fuseki
      run: ls -lR /opt/fuseki && cd /opt/fuseki && sudo nohup /opt/fuseki/fuskei-server --port=8090 --tdb2 --loc=/data --update /pi
      env:
        FUSEKI_HOME: /opt/fuseki
    - name: Symlink directory
      run: sudo mkdir -p /srv/data/papyri.info/git/ && sudo ln -s "$(pwd)" /srv/data/papyri.info/git/navigator
    - name: Cache idp.data
      uses: actions/cache@v2
      with:
        path: /srv/data/papyri.info/idp.data
        key: ${{ runner.os }}-idp-data
    - name: Clone idp.data
      run: cd /srv/data/papyri.info && sudo git clone https://github.com/papyri/idp.data.git
    - name: Run pn-dispatcher tests
      run: cd pn-dispatcher && mvn test
    - name: Run pn-sync tests
      run: cd pn-sync && mvn test
