# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will download a prebuilt Ruby version, install dependencies and run tests with Rake
# For more information see: https://github.com/marketplace/actions/setup-ruby-jruby-and-truffleruby

name: Run Tests

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Cache Java Packages
      uses: actions/cache@v2
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-m2
    - name: Run pn-dispatcher tests
      run: cd pn-dispatcher && mvn test
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    # - name: Install dependencies
    # run: sudo apt-get update && sudo apt-get install -y libcurl4-openssl-dev openjdk-11-jdk-headless maven git perl tar wget curl
    # - name: Symlink directory
    #   run: sudo mkdir -p /srv/data/papyri.info/git/ && sudo ln -s "$(pwd)" /srv/data/papyri.info/git/navigator
    # - name: Cache idp.data
    #   uses: actions/cache@v2
    #   id: cache-idp-data
    #   with:
    #     path: /srv/data/papyri.info/idp.data
    #     key: ${{ runner.os }}-idp-data-clone
    # - name: Clone idp.data
    #   if: steps.cache-idp-data.outputs.cache-hit != 'true'
    #   run: cd /srv/data/papyri.info && sudo git clone https://github.com/papyri/idp.data.git
    # - name: Install Fuseki
    #   run: sudo mkdir -p /opt/fuseki && wget --no-check-certificate https://archive.apache.org/dist/jena/binaries/apache-jena-fuseki-3.17.0.tar.gz -O-|sudo tar -zx --strip-components 1 -C /opt/fuseki/ apache-jena-fuseki-3.17.0
    # - name: Run Fuseki
    #   run: cd /opt/fuseki && sudo nohup ./fuseki-server --port=8090 --tdb2 --loc=/data --update /pi &
    #   env:
    #     FUSEKI_HOME: /opt/fuseki
    # - name: Run pn-sync tests
    #   run: cd pn-sync && mvn test
